### ISSUE TITLE
Improve usability at tool start

### ISSUE THREAD

**Issue by annaeg** [pericles-project/pet#16]
Currently all existing Extraction Modules are loaded to the default profile at the first tool start. This is good for presentations, but less good for real usages. Better would be to load no module and to display a text to the user that Extraction Modules should be added to the profile.

Furthermore some "first steps" help could be displayed at the first tool start.

**Comment by corubolo** [comment]
Issue solved with 9c20d55935368a272e5d789f59a2d23d0b78af78
