### ISSUE TITLE
Refactor the GUI to make the scope of help- and profile-tab obvious

### ISSUE THREAD

**Issue by annaeg** [pericles-project/pet#2]
The GUI help-tab and the event-tab are independent of the created profiles. The event-tab shows events of monitoring daemons from all profiles, so that it can be tracked if an event triggers the execution of extraction modules from other profiles, which is possible.

At the moment the GUI looks like these tabs belong to the profiles. This should be change to make the scope of the tabls clear.

**Comment by corubolo** [comment]
Improved in last GUI refactor
